export default function transformData(originalData) {
  return {
    order: {
      type: originalData['furniture-type'] || '',
      name: originalData['furniture-name'] || '',
      payment: {
        status: originalData.paymentStatus || 'false',
        method: originalData.paymentMethod || '',
      },
      dimensions: {
        width: originalData['furniture-dimension-w'] || '',
        height: originalData['furniture-dimension-h'] || '',
        length: originalData['furniture-dimension-l'] || '',
      },
      specialFunction: originalData['special-functions'] || '',
      specialFunctionScene: false,
      material: originalData['color-finish'] || '',
      color: '',
      images: [],
      extras: {
        viewangles: originalData['render-extra-viewangle'] || '',
        lightPreferences: originalData['lighting-comment'] || '',
        roomType: originalData['room-type'] || '',
      },
      renderPackage: originalData['package-select'] || '',
      roomTypeDescription: originalData['dimensions-comment'] || '',
      metadata: {
        categoryComment: originalData['category-comment'] || '',
        categoryWood: originalData['category-wood'] || '',
        categoryMetal: originalData['category-metal'] || '',
        categoryPlastic: originalData['category-plastic'] || '',
        categoryStone: originalData['category-stone'] || '',
        categoryGlass: originalData['category-glass'] || '',
        commentMaterial: originalData['comment-material'] || '',
        commentWood: originalData['Comment-Wood'] || '',
        materialOak: originalData['material-oak'] || '',
        materialWalnut: originalData['material-walnut'] || '',
        materialBeech: originalData['material-beech'] || '',
        materialWhiteOak: originalData['material-whiteoak'] || '',
        materialSteel: originalData['material-steel'] || '',
        materialAluminium: originalData['material-aluminium'] || '',
        materialBrass: originalData['material-brass'] || '',
        commentToggleMetal: originalData['comment-toggle-metal'] || '',
        commentMetal: originalData['Comment-Metal'] || '',
        materialAcrylic: originalData['material-acrylic'] || '',
        materialPolyethylene: originalData['material-polyethylene'] || '',
        materialPVC: originalData['material-pvc'] || '',
        commentPlastic: originalData['Comment-Plastic'] || '',
        materialMarble: originalData['material-marble'] || '',
        materialGranite: originalData['material-granite'] || '',
        materialQuartz: originalData['material-quartz'] || '',
        commentStone: originalData['Comment-Stone'] || '',
        materialTempredGlass: originalData['material-tempredglass'] || '',
        materialFrostedGlass: originalData['material-frostedglass'] || '',
        commentGlass: originalData['Comment-Glass'] || '',
        lightingMorning: originalData['lighting-morning'] || '',
        lightingNoon: originalData['lighting-noon'] || '',
        lightingComment: originalData['lighting-comment'] || '',
        functionShow: originalData['function-show'] || '',
      },
    },
  };
}
