name: CI

on:
  pull_request:

jobs:
  Lint:
    uses: finsweet/workflow-ci-lint/.github/workflows/lint.yml@main

  Build:
    steps:
      - name: Install dependencies
      # run: pnpm install --frozen-lockfile
      # If you don't have a lockfile, use this instead:
      run: pnpm install --no-frozen-lockfile
  # Comment this job out if your project doesn't have any tests.
  #Tests:
  # uses: finsweet/workflow-ci-test/.github/workflows/test.yml@main
